// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'juso_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

JusoModel _$JusoModelFromJson(Map<String, dynamic> json) => JusoModel(
      roadFullAddr: json['roadFullAddr'] as String?,
      roadAddr: json['roadAddr'] as String?,
      roadAddrPart1: json['roadAddrPart1'] as String?,
      roadAddrPart2: json['roadAddrPart2'] as String?,
      jibunAddr: json['jibunAddr'] as String?,
      engAddr: json['engAddr'] as String?,
      addrDetail: json['addrDetail'] as String?,
      zipNo: json['zipNo'] as String?,
      admCd: json['admCd'] as String?,
      rnMgtSn: json['rnMgtSn'] as String?,
      bdMgtSn: json['bdMgtSn'] as String?,
      detBdNmList: json['detBdNmList'] as String?,
      bdNm: json['bdNm'] as String?,
      bdKdcd: json['bdKdcd'] as String?,
      siNm: json['siNm'] as String?,
      sggNm: json['sggNm'] as String?,
      emdNm: json['emdNm'] as String?,
      liNm: json['liNm'] as String?,
      rn: json['rn'] as String?,
      udrtYn: json['udrtYn'] as String?,
      buldMnnm: json['buldMnnm'] as String?,
      buldSlno: json['buldSlno'] as String?,
      mtYn: json['mtYn'] as String?,
      lnbrMnnm: json['lnbrMnnm'] as String?,
      lnbrSlno: json['lnbrSlno'] as String?,
      emdNo: json['emdNo'] as String?,
      hstryYn: json['hstryYn'] as String?,
      relJibun: json['relJibun'] as String?,
      hemdNm: json['hemdNm'] as String?,
      entX: json['entX'] as String?,
      entY: json['entY'] as String?,
    );

Map<String, dynamic> _$JusoModelToJson(JusoModel instance) => <String, dynamic>{
      'roadFullAddr': instance.roadFullAddr,
      'roadAddr': instance.roadAddr,
      'roadAddrPart1': instance.roadAddrPart1,
      'roadAddrPart2': instance.roadAddrPart2,
      'jibunAddr': instance.jibunAddr,
      'engAddr': instance.engAddr,
      'addrDetail': instance.addrDetail,
      'zipNo': instance.zipNo,
      'admCd': instance.admCd,
      'rnMgtSn': instance.rnMgtSn,
      'bdMgtSn': instance.bdMgtSn,
      'detBdNmList': instance.detBdNmList,
      'bdNm': instance.bdNm,
      'bdKdcd': instance.bdKdcd,
      'siNm': instance.siNm,
      'sggNm': instance.sggNm,
      'emdNm': instance.emdNm,
      'liNm': instance.liNm,
      'rn': instance.rn,
      'udrtYn': instance.udrtYn,
      'buldMnnm': instance.buldMnnm,
      'buldSlno': instance.buldSlno,
      'mtYn': instance.mtYn,
      'lnbrMnnm': instance.lnbrMnnm,
      'lnbrSlno': instance.lnbrSlno,
      'emdNo': instance.emdNo,
      'hstryYn': instance.hstryYn,
      'relJibun': instance.relJibun,
      'hemdNm': instance.hemdNm,
      'entX': instance.entX,
      'entY': instance.entY,
    };
